Htsget CDK: Added GA4GH Passport support
umccr/infrastructure pull request #101
Opened 2021-01-27 01:27 UTC by victorskl

* Added Lambda authorizer as well as built-in AWS_IAM authorizer
  to API Gateway v2 for some experimental htsget endpoints
* Passport Clearinghouse is implemented as AWS Lambda function
* Updated CDK deployment: include Lambda and Lambda Layer for
  Python dependencies packaging
* Updated CDK deployment: added experimental htsget routes to
  collab work with Guppy/Asha genovic.org.au Passport Brokers
* Updated README for Lambda Development

2021-01-27 02:04 UTC, victorskl commented
**Summary:**

- This is follow up PR to support GA4GH Passport to htsget on top of CORS support added in https://github.com/ga4gh/htsget-refserver/pull/24
- This basically add baseline implementation for GA4GH Passport protected htsget endpoint for some selected route (POC).
- This can be tested immediately as follows:
```
curl -s https://htsget.dev.umccr.org/reads/giab.NA12878.NIST7086.2 | jq
{
  "message": "Unauthorized"
}

export PASSPORT_VISA_TOKEN=<tok>
curl -s -H "Authorization: Bearer $PASSPORT_VISA_TOKEN" -X GET https://htsget.dev.umccr.org/reads/giab.NA12878.NIST7086.2 | jq
```
- And then, you can observe Lambda logs from CloudWatch Console or CLI as follows:
```
aws logs get-log-events --log-group-name '/aws/lambda/htsget_passport_authz_lambda' --log-stream-name '2021/01/27/[$LATEST]f0abe9e1d9e349908f13f127aa28b98b' --limit 100 --profile dev
```
- You can get Passport Visa Token from Labtec/Guppy/Asha Passport Broker service
- Unlike issue discussed for DRS https://github.com/ga4gh/data-repository-service-schemas/issues/339, htsget API as no list of dataset view (i.e. no selection). Hence, as a baseline implementation, it is just straight mapping for protected route(s) to a particular Passport Visa Token that is (has to be?) provided by a client. Hence, selection of an appropriate Passport Visa Token from a Passport (i.e. Passport down-scoping issue) is left to a caller, at the moment. 
- In fact, this Lambda Passport Clearinghouse implementation is very much similar previous [UMCCR contrib to PanelApp Cognito integration](https://gitlab.com/genomicsengland/panelapp/panelapp/-/blob/master/panelapp/panelapp/cognito/middleware.py). 
- Some screenshots are as follows:
![ga4gh_passport_htsget_1](https://user-images.githubusercontent.com/4586509/105930234-64128780-609d-11eb-8c18-c4767051cbcf.png)
![ga4gh_passport_htsget_2](https://user-images.githubusercontent.com/4586509/105930237-67a60e80-609d-11eb-9ab8-06896d4af10e.png)
![ga4gh_passport_htsget_3](https://user-images.githubusercontent.com/4586509/105930239-68d73b80-609d-11eb-978a-0803f6949991.png)

**Further Works:**
- A couple of way to improve this baseline POC implementation
- Add Passport Clearinghouse functionality directly into htsget? (i.e. eliminate Lambda calls, reduce network hopping around)
- Possible streamline configuration (or UI) facility for Passport Visa Token ACL (Access Control)
- Make robust to Passport Clearinghouse conformance and testing
- Also setup UMCCR Passport Broker?
- UMCCR Data Portal IGV.js integration: support Passport or AWS_IAM?

/cc @ohofmann @brainstorm @reisingerf @andrewpatto

2021-01-27 02:27 UTC, victorskl commented
@reisingerf Ping for checking out _Python dependencies as Lambda Layer with CDK_ and, setup for _Lambda Python unit test_. 😃

2021-01-27 04:32 UTC, brainstorm approved these changes
This is soooo good @victorskl, kudos! Really enjoyed reviewing this pullrequest after our shared struggles understanding GA4GH's auth schemes :D

2021-01-27 04:50 UTC, brainstorm commented
Not merging yet since some of the FIXMEs are rather serious if merged & deployed.

2021-01-27 04:50 UTC, brainstorm requested changes
FIXMEs must be addressed before merging into master.

2021-01-27 22:23 UTC, victorskl commented
Ah right! Yap, probably we should opt out those. I will amend the commit to address those FIXMEs today.

2021-01-31 21:49 UTC, victorskl commented
> Very minor detail, but I'd bump to PYTHON_3_8 since AWS SecurityHub complains about "update your lambda python runtime" otherwise ;)

Right, yep. Sound good. I will update it today.

2021-02-12 00:41 UTC, victorskl commented
@brainstorm Anything you want to note? Otherwise, I want to merge this.

2021-02-12 00:47 UTC, merged